import { NextRequest, NextResponse } from 'next/server'
import { dataverseFetch } from '@/lib/borealis'

export async function POST(req: NextRequest) {
  try {
    const { pid, token, markdown, signedUrl, siteUrl } = await req.json()

    if (!pid || !markdown) {
      return NextResponse.json({ message: 'Missing pid or markdown' }, { status: 400 })
    }

    if (!signedUrl && !token) {
      return NextResponse.json({ message: 'Missing token or signed URL' }, { status: 400 })
    }

    // Check existing files to determine README filename
    let filename = 'README.md'
    try {
      const filesRes = signedUrl
        ? await fetch(signedUrl.replace('/add?', '/versions/:latest/files?'))
        : await dataverseFetch(
            `/api/v1/datasets/:persistentId/versions/:latest/files?persistentId=${encodeURIComponent(pid)}`,
            token,
            siteUrl
          )
      if (filesRes.ok) {
        const filesJson = await filesRes.json()
        const existingNames: string[] = (filesJson.data || []).map((f: { label: string }) => f.label)
        let n = 2
        while (existingNames.includes(filename)) {
          filename = `README_${n}.md`
          n++
        }
      }
    } catch {
      // If we can't check, just use README.md
    }

    const boundary = `----FormBoundary${Math.random().toString(16).slice(2)}`

    const metaPart = JSON.stringify({
      description: 'README generated by Borealis README.gen',
      categories: ['Documentation'],
      restrict: false,
    })

    const body = [
      `--${boundary}`,
      `Content-Disposition: form-data; name="jsonData"`,
      '',
      metaPart,
      `--${boundary}`,
      `Content-Disposition: form-data; name="file"; filename="${filename}"`,
      `Content-Type: text/markdown`,
      '',
      markdown,
      `--${boundary}--`,
    ].join('\r\n')

    const uploadUrl = signedUrl
      ? signedUrl
      : `${siteUrl || 'https://borealisdata.ca'}/api/v1/datasets/:persistentId/add?persistentId=${encodeURIComponent(pid)}`

    const headers: Record<string, string> = {
      'Content-Type': `multipart/form-data; boundary=${boundary}`,
      'Content-Length': Buffer.byteLength(body).toString(),
    }
    if (token) headers['X-Dataverse-key'] = token

    const res = await fetch(uploadUrl, { method: 'POST', headers, body })

    if (!res.ok) {
      const err = await res.json().catch(() => ({}))
      return NextResponse.json(
        { message: (err as { message?: string }).message || `Dataverse returned ${res.status}` },
        { status: res.status }
      )
    }

    return NextResponse.json({ ok: true, filename })
  } catch (e) {
    return NextResponse.json({ message: String(e) }, { status: 500 })
  }
}
