import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const { pid, token, markdown, signedUrl, siteUrl, filename } = await req.json()

    if (!markdown) {
      return NextResponse.json({ message: 'Missing markdown' }, { status: 400 })
    }
    if (!signedUrl && !pid) {
      return NextResponse.json({ message: 'Missing pid or signed URL' }, { status: 400 })
    }
    if (!signedUrl && !token) {
      return NextResponse.json({ message: 'Missing token or signed URL' }, { status: 400 })
    }

    console.log('[save] filename received:', JSON.stringify(filename))
    const finalFilename = filename || 'README.md'

    // FormData rather than a hand-built body: the previous version joined the
    // parts as a JS string while setting Content-Length from Buffer.byteLength,
    // so any multi-byte character (accented names, French metadata, em dashes)
    // produced a length mismatch and a malformed upload. Letting fetch build the
    // body also means it sets the boundary itself.
    const form = new FormData()
    form.append(
      'jsonData',
      JSON.stringify({
        label: finalFilename,
        description: 'README generated by Borealis README.gen',
        categories: ['Documentation'],
        restrict: false,
      })
    )
    form.append(
      'file',
      new Blob([markdown], { type: 'text/markdown' }),
      finalFilename
    )

    // A signed URL is opaque — send it exactly as received. Note it already
    // carries the caller's authorisation, so no API token is attached with it.
    const uploadUrl = signedUrl
      ? signedUrl
      : `${siteUrl || 'https://borealisdata.ca'}/api/v1/datasets/:persistentId/add?persistentId=${encodeURIComponent(pid)}`

    const headers: Record<string, string> = {}
    if (!signedUrl && token) headers['X-Dataverse-key'] = token

    const res = await fetch(uploadUrl, { method: 'POST', headers, body: form })

    if (!res.ok) {
      const err = await res.json().catch(() => ({}))
      return NextResponse.json(
        { message: (err as { message?: string }).message || `Dataverse returned ${res.status}` },
        { status: res.status }
      )
    }

    return NextResponse.json({ ok: true, filename: finalFilename })
  } catch (e) {
    return NextResponse.json({ message: String(e) }, { status: 500 })
  }
}
